[package]
name = "qsd"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "1.3.0"
gtk = "*"
cli-clipboard = "0.3.0"
youtube_dl = "0.7.0"
dirs = "4.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
